name: reminder_app_challenge
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  bloc: ^8.1.4
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_local_notifications: ^17.1.2
  flutter_slidable: ^3.1.0
  flutter_timezone: ^1.0.8
  geolocator: ^12.0.0
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  notification_permissions: ^0.6.1
  path_provider: ^2.1.3

dev_dependencies:
  build_runner: 2.4.9
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - 'assets/'
